import type { MarketAnalysis } from '../types'

export function generateReportMarkdown(
  title: string,
  region: string,
  report: MarketAnalysis
): string {
  const date = new Date().toLocaleDateString('en-US')

  return `# Market Analysis: ${title}
**Region:** ${region || 'Local/Not specified'}
**Date:** ${date}
**Score:** ${report.scoreAtGeneration}/100

## Summary
${report.verdict}

## Market Metrics
- **Competition:** ${report.metrics.competition}
- **Search Volume:** ${report.metrics.searchVolume}
- **Trend:** ${report.metrics.trend}
- **CPC (Ads):** ${report.metrics.cpc}
${report.metrics.totalResults ? `- **Google Results:** ${report.metrics.totalResults.toLocaleString('en-US')}` : ''}

## SWOT Analysis
### Strengths
${report.swot.strengths.map(s => `- ${s}`).join('\n')}

### Weaknesses
${report.swot.weaknesses.map(s => `- ${s}`).join('\n')}

### Opportunities
${report.swot.opportunities.map(s => `- ${s}`).join('\n')}

### Threats
${report.swot.threats.map(s => `- ${s}`).join('\n')}

## Target Audience (Persona)
**Name:** ${report.persona.name}
**Pain Points:** ${report.persona.painPoints.join(', ')}
**Willingness to Pay:** ${report.persona.willingnessToPay}

## Strategy & Revenue Models
**Go-to-Market Strategy:**
${report.strategyRecommendation}

**Recommended Revenue Models:**
${report.revenueModels.map(m => `- ${m}`).join('\n')}

## Next Steps
${report.nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

---
*Generated by Idea Scout - Local Demand Engine*
`
}